[package]
name = "lariv-plugin-import"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Lariv import plugin"

[features]
plugin-export = ["dep:lariv-plugin-export"]

[dependencies]
lariv_core = { package = "lariv-core", path = "../../lariv-core" }
lariv-rs-macros = { workspace = true }
lariv-plugin-users = { path = "../users" }
lariv-plugin-export = { path = "../export", optional = true }
axum = { workspace = true }
calamine = { workspace = true }
chrono = { workspace = true }
frunk = { workspace = true }
frunk_core = { workspace = true }
http = { workspace = true }
maud = { workspace = true }
rust_xlsxwriter = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
