database_url = "sqlite://lariv.db?mode=rwc"
bind = "0.0.0.0:3000"

[users]
adminEmail = "admin@example.com"
adminPassword = "adminadmin"

[filesystem]
storageBackend = "local"
localDir = "filesystem"
# gcsBucket = ""
# gcsCredentialsFile = ""
# gcsPrefix = ""

[pwa]
PWA_APP_NAME = "Lariv"
PWA_APP_DESCRIPTION = "Lariv Progressive Web App"
PWA_APP_THEME_COLOR = "#0f172a"
PWA_APP_BACKGROUND_COLOR = "#ffffff"
PWA_APP_DISPLAY = "standalone"
PWA_APP_SCOPE = "/"
PWA_APP_ORIENTATION = "any"
PWA_APP_START_URL = "/"
PWA_APP_DIR = "ltr"
PWA_APP_LANG = "en-US"
# staticDir = "./pwa_static"
