//! Typed route tags and response-kind markers for compile-time HTMX wiring checks.
//!
//! Route tags are generated by [`crate::define_plugin_routes!`] with typed path fields,
//! `path()` / `url()` builders, and response marker traits.

use std::fmt::Display;

use crate::components::swap::SwapKey;

/// Plugin route identity with a static path pattern.
pub trait RouteTag {
    const PATH: &'static str;

    /// Path template placeholders (e.g. `["id"]`, `["parent_id"]`), when known.
    const PARAMS: &'static [&'static str] = &[];
}

/// Build URLs from a typed route value (generated by [`crate::define_plugin_routes!`]).
pub trait RouteUrl: RouteTag + Sized {
    fn path(self) -> String;
    fn url(self) -> String;
}

/// GET returns a full app pane (`#app-layout`).
pub trait AppPaneGet: RouteTag {}

/// POST replaces `#app-layout` (form create/edit).
pub trait AppPanePost: RouteTag {}

/// GET returns a partial for the given [`SwapKey`] region (filters, tables).
pub trait FragmentGet<K: SwapKey>: RouteTag {}

/// POST targets the given [`SwapKey`] region (modal confirm, table action).
pub trait FragmentPost<K: SwapKey>: RouteTag {}

/// GET returns a file attachment (plain link, `hx-boost=false`).
pub trait FileDownloadGet: RouteTag {}

/// POST returns a file attachment (plain form, no HTMX swap).
pub trait FileDownloadPost: RouteTag {}

/// GET returns modal markup appended to `document.body`.
pub trait ModalGet: RouteTag {}

/// POST via hx-boost into `#app-layout` (logout-style).
pub trait BoostPost: RouteTag {}

/// POST into a dynamic generation poll region (gen_poll helpers).
pub trait GenerationPost: RouteTag {}

/// Fluent query-string builder wrapping a typed route.
pub struct RouteQueryBuilder<R: RouteUrl> {
    route: R,
    query: Vec<(String, String)>,
}

impl<R: RouteUrl> RouteQueryBuilder<R> {
    pub fn new(route: R) -> Self {
        Self {
            route,
            query: Vec::new(),
        }
    }

    /// Append a query-string pair (values are percent-encoded).
    pub fn query(mut self, key: &str, value: impl Display) -> Self {
        self.query.push((key.to_owned(), value.to_string()));
        self
    }

    /// Append a query pair when `value` is present.
    pub fn query_opt(self, key: &str, value: Option<impl Display>) -> Self {
        match value {
            Some(v) => self.query(key, v),
            None => self,
        }
    }

    /// Path without trailing slash but with optional `?query` (for hx-post/action attrs).
    pub fn build_with_query(self) -> String {
        append_query(self.route.path(), &self.query)
    }

    /// Path with trailing slash and optional `?query` (for navigation hrefs).
    pub fn build(self) -> String {
        let path = trailing_slash(&self.route.path());
        append_query(path, &self.query)
    }
}

/// Append trailing slash for URLs used in templates (Axum routes omit it).
pub fn trailing_slash(path: &str) -> String {
    if path.is_empty() || path.ends_with('/') {
        path.to_owned()
    } else {
        format!("{path}/")
    }
}

fn append_query(path: String, query: &[(String, String)]) -> String {
    if query.is_empty() {
        return path;
    }
    let mut out = path;
    out.push('?');
    for (i, (key, value)) in query.iter().enumerate() {
        if i > 0 {
            out.push('&');
        }
        encode_query_component(&mut out, key);
        out.push('=');
        encode_query_component(&mut out, value);
    }
    out
}

fn encode_query_component(out: &mut String, s: &str) {
    for b in s.bytes() {
        match b {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => {
                out.push(char::from(b));
            }
            _ => {
                out.push('%');
                out.push(char::from(b"0123456789ABCDEF"[(b >> 4) as usize]));
                out.push(char::from(b"0123456789ABCDEF"[(b & 0xf) as usize]));
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    struct TestIdRoute {
        id: i64,
    }

    impl RouteTag for TestIdRoute {
        const PATH: &'static str = "/items/{id}/edit";
        const PARAMS: &'static [&'static str] = &["id"];
    }

    impl RouteUrl for TestIdRoute {
        fn path(self) -> String {
            format!("/items/{}/edit", self.id)
        }

        fn url(self) -> String {
            trailing_slash(&self.path())
        }
    }

    struct TestStaticRoute;

    impl RouteTag for TestStaticRoute {
        const PATH: &'static str = "/proposals/create";
    }

    impl RouteUrl for TestStaticRoute {
        fn path(self) -> String {
            Self::PATH.to_owned()
        }

        fn url(self) -> String {
            trailing_slash(&self.path())
        }
    }

    #[test]
    fn route_url_adds_slash() {
        assert_eq!(TestStaticRoute.url(), "/proposals/create/");
        assert_eq!(TestIdRoute { id: 1 }.url(), "/items/1/edit/");
    }

    #[test]
    fn query_params_and_encoding() {
        assert_eq!(
            RouteQueryBuilder::new(TestStaticRoute)
                .query("ClientID", 42)
                .query("return", "client")
                .build_with_query(),
            "/proposals/create?ClientID=42&return=client"
        );
        assert_eq!(
            RouteQueryBuilder::new(TestStaticRoute)
                .query("identifier", "a+b")
                .build_with_query(),
            "/proposals/create?identifier=a%2Bb"
        );
    }

    #[test]
    fn query_opt_skips_none() {
        assert_eq!(
            RouteQueryBuilder::new(TestStaticRoute)
                .query("ClientID", 1)
                .query_opt("return", None::<&str>)
                .build_with_query(),
            "/proposals/create?ClientID=1"
        );
    }
}
