[package]
name = "lariv-plugin-users"
version = "0.1.0"
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Lariv users plugin"

[features]
default = []

[dependencies]
lariv_core = { package = "lariv-core", path = "../../lariv-core" }
lariv-rs-macros = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
frunk = { workspace = true }
frunk_core = { workspace = true }
http = { workspace = true }
jsonwebtoken = { workspace = true }
maud = { workspace = true }
phonenumber = { workspace = true }
rand = { workspace = true }
scrypt = { workspace = true }
sea-orm = { workspace = true }
sea-orm-migration = { workspace = true }
serde = { workspace = true }
subtle = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[lints]
workspace = true
