pub mod company;
pub mod completed_task;
pub mod contact;
pub mod converted_lead;
pub mod failed_lead;
pub mod lead;
pub mod lead_tag;
pub mod lead_tag_link;
pub mod lead_update;
pub mod task;

pub use company::Entity as CompanyEntity;
pub use completed_task::Entity as CompletedTaskEntity;
pub use contact::Entity as ContactEntity;
pub use converted_lead::Entity as ConvertedLeadEntity;
pub use failed_lead::Entity as FailedLeadEntity;
pub use lead::Entity as LeadEntity;
pub use lead_tag::Entity as LeadTagEntity;
pub use lead_tag_link::Entity as LeadTagLinkEntity;
pub use lead_update::Entity as LeadUpdateEntity;
pub use task::Entity as TaskEntity;
