crate::swap_key!(LeadHubTableKey, "crm-lead-hub-table");
crate::swap_key!(LeadCreateModalKey, "crm-lead-create-modal");
crate::swap_key!(LeadEditModalKey, "crm-lead-edit-modal");
crate::swap_key!(LeadDeleteModalKey, "crm-lead-delete-modal");
crate::swap_key!(LeadConvertModalKey, "crm-lead-convert-modal");
crate::swap_key!(LeadFailModalKey, "crm-lead-fail-modal");
crate::swap_key!(TaskTableKey, "crm-task-table");
crate::swap_key!(TaskCreateModalKey, "crm-task-create-modal");
crate::swap_key!(TaskEditModalKey, "crm-task-edit-modal");
crate::swap_key!(TaskDeleteModalKey, "crm-task-delete-modal");
crate::swap_key!(LeadUpdatesKey, "crm-lead-updates");
/// HTMX `HX-Trigger` / Alpine event after a lead update is saved from the detail form.
pub const LEAD_UPDATE_SAVED_EVENT: &str = "crm-lead-update-saved";
crate::swap_key!(LeadUpdateEditModalKey, "crm-lead-update-edit-modal");
crate::swap_key!(LeadUpdateDeleteModalKey, "crm-lead-update-delete-modal");
crate::swap_key!(LeadTagTableKey, "crm-lead-tag-table");
crate::swap_key!(LeadTagLeadsTableKey, "crm-lead-tag-leads-table");
crate::swap_key!(LeadTagSelectTableKey, "crm-lead-tag-select-table");
crate::swap_key!(LeadTagSelectModalKey, "crm-lead-tag-select-modal");
crate::swap_key!(LeadTagCreateModalKey, "crm-lead-tag-create-modal");
crate::swap_key!(LeadTagEditModalKey, "crm-lead-tag-edit-modal");
crate::swap_key!(LeadTagDeleteModalKey, "crm-lead-tag-delete-modal");
