use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(OtpPreferences::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(OtpPreferences::Id)
                            .big_integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(OtpPreferences::CreatedAt).timestamp_with_time_zone())
                    .col(ColumnDef::new(OtpPreferences::UpdatedAt).timestamp_with_time_zone())
                    .col(ColumnDef::new(OtpPreferences::DeletedAt).timestamp_with_time_zone())
                    .col(
                        ColumnDef::new(OtpPreferences::SmsOtpTemplateId)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(OtpPreferences::OtpTemplateId)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(OtpPreferences::Msg91AuthKey)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(OtpPreferences::SmsOtpFieldName)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(OtpPreferences::SmsOtpExtraFields)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(OtpPreferences::EmailOtpTemplateString)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(OtpPreferences::SmtpHost)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(OtpPreferences::SmtpPort)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(OtpPreferences::SmtpUsername)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(OtpPreferences::SmtpPassword)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .col(
                        ColumnDef::new(OtpPreferences::SmtpFrom)
                            .text()
                            .not_null()
                            .default(""),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .if_not_exists()
                    .name("idx_otp_preferences_deleted_at")
                    .table(OtpPreferences::Table)
                    .col(OtpPreferences::DeletedAt)
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(OtpPreferences::Table).to_owned())
            .await
    }
}

#[derive(DeriveIden)]
enum OtpPreferences {
    Table,
    Id,
    CreatedAt,
    UpdatedAt,
    DeletedAt,
    SmsOtpTemplateId,
    OtpTemplateId,
    Msg91AuthKey,
    SmsOtpFieldName,
    SmsOtpExtraFields,
    EmailOtpTemplateString,
    SmtpHost,
    SmtpPort,
    SmtpUsername,
    SmtpPassword,
    SmtpFrom,
}
