//! Bundled Lariv plugins for standard web application capabilities.
//!
//! Each plugin exposes an `install(app) -> App<…>` function (generated by
//! [`define_plugin_install!`](crate::plugin_install::define_plugin_install)) that
//! registers routes, templates, migrations, config sections, and runtime state.
//!
//! # Plugins
//!
//! | Module | Purpose |
//! |--------|---------|
//! | [`users`] | Authentication, roles, user administration |
//! | [`dashboard`] | Apps launchpad portal and home redirects |
//! | [`blog`] | Articles and hierarchical tags |
//! | [`filesystem`] | DB-backed virtual filesystem and blob storage |
//! | [`website`] | DB routes, Minijinja pages, GrapesJS builder |
//! | [`llm_assistant`] | Gemini chat, skills, session history, WebSocket |
//! | [`otp`] | Password recovery via SMS (MSG91) / SMTP |
//! | [`pwa`] | Manifest, service worker, offline page |
//! | [`export`] | XLSX data export UI |
//! | [`no_signup`] | Disables public signup routes and UI |
//!
//! # Examples
//!
//! ```ignore
//! use lariv_rs::app::App;
//! use lariv_rs::plugins::{users, dashboard, blog};
//!
//! let app = App::new_web_app();
//! let app = users::install(app);
//! let app = dashboard::install(app);
//! let app = blog::install(app);
//! ```

pub mod blog;
pub mod dashboard;
pub mod export;
pub mod filesystem;
pub mod llm_assistant;
pub mod no_signup;
pub mod otp;
pub mod pwa;
pub mod users;
pub mod website;
